/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package com.aman.gui;

import com.aman.pojo.User;
import java.awt.Color;
import java.awt.Graphics;
import javax.swing.JComponent;
import javax.swing.JMenuBar;
import javax.swing.JOptionPane;
import javax.swing.plaf.basic.BasicMenuBarUI;

/**
 *
 * @author vivek
 */
public class AdminPage extends javax.swing.JFrame {

    /**
     * Creates new form AdminPage
     */
    User user;
    public AdminPage() {
        initComponents();
        this.setLocationRelativeTo(null);
        customiseMenuBar(jMenuBar1);
        advertlabel.setText("Bookings Made Easier!");
    }
    public AdminPage(User user)
    {
        this();
        this.user=user;
        WelcomeLabel.setText("Hello "+user.getUsername());
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        advertlabel = new javax.swing.JLabel();
        WelcomeLabel = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        homeMenu = new javax.swing.JMenu();
        EventsMenu = new javax.swing.JMenu();
        ViewEventsMenu = new javax.swing.JMenuItem();
        AddEventsMenu = new javax.swing.JMenuItem();
        AgentsMenu = new javax.swing.JMenu();
        AddAgentsMenu = new javax.swing.JMenuItem();
        ViewAgentsMenu = new javax.swing.JMenuItem();
        User = new javax.swing.JMenu();
        AddUser = new javax.swing.JMenuItem();
        ViewUsers = new javax.swing.JMenuItem();
        bookings = new javax.swing.JMenu();
        logout = new javax.swing.JMenu();

        jLabel4.setText("jLabel4");

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/aman/images/iconimg.jpg"))); // NOI18N
        jLabel1.setText("jLabel1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setSize(new java.awt.Dimension(0, 0));

        jPanel1.setBackground(new java.awt.Color(204, 204, 255));

        advertlabel.setFont(new java.awt.Font("Dialog", 3, 18)); // NOI18N
        advertlabel.setForeground(new java.awt.Color(204, 204, 204));
        advertlabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        advertlabel.setText("Bookings Made Easy");

        WelcomeLabel.setFont(new java.awt.Font("Dialog", 3, 18)); // NOI18N
        WelcomeLabel.setForeground(new java.awt.Color(0, 153, 0));
        WelcomeLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        WelcomeLabel.setText("jLabel1");

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/aman/images/soccer-field-top-view-empty-football-stadium-vector-20649350.png"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(100, 100, 100)
                        .addComponent(WelcomeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 265, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(advertlabel, javax.swing.GroupLayout.PREFERRED_SIZE, 420, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 510, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(24, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(WelcomeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(120, 120, 120)
                .addComponent(advertlabel, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        jMenuBar1.setBackground(new java.awt.Color(0, 0, 0));
        jMenuBar1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        jMenuBar1.setForeground(new java.awt.Color(255, 255, 255));
        jMenuBar1.setOpaque(false);

        homeMenu.setBackground(new java.awt.Color(0, 0, 0));
        homeMenu.setText("Home");
        homeMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                homeMenuActionPerformed(evt);
            }
        });
        jMenuBar1.add(homeMenu);

        EventsMenu.setBackground(new java.awt.Color(0, 0, 0));
        EventsMenu.setText("Events");

        ViewEventsMenu.setText("View Events");
        ViewEventsMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ViewEventsMenuActionPerformed(evt);
            }
        });
        EventsMenu.add(ViewEventsMenu);

        AddEventsMenu.setText("Add Events");
        AddEventsMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddEventsMenuActionPerformed(evt);
            }
        });
        EventsMenu.add(AddEventsMenu);

        jMenuBar1.add(EventsMenu);

        AgentsMenu.setText("Agents");

        AddAgentsMenu.setText("Add Agents");
        AddAgentsMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddAgentsMenuActionPerformed(evt);
            }
        });
        AgentsMenu.add(AddAgentsMenu);

        ViewAgentsMenu.setText("View Agents");
        ViewAgentsMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ViewAgentsMenuActionPerformed(evt);
            }
        });
        AgentsMenu.add(ViewAgentsMenu);

        jMenuBar1.add(AgentsMenu);

        User.setText("User");

        AddUser.setText("Add User");
        AddUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddUserActionPerformed(evt);
            }
        });
        User.add(AddUser);

        ViewUsers.setText("View Users");
        ViewUsers.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ViewUsersActionPerformed(evt);
            }
        });
        User.add(ViewUsers);

        jMenuBar1.add(User);

        bookings.setText("Bookings");
        bookings.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bookingsMouseClicked(evt);
            }
        });
        jMenuBar1.add(bookings);

        logout.setText("Logout");
        logout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                logoutMousePressed(evt);
            }
        });
        logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutActionPerformed(evt);
            }
        });
        jMenuBar1.add(logout);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void homeMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_homeMenuActionPerformed
        // TODO add your handling code here:
        new AdminPage(user).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_homeMenuActionPerformed

    private void ViewEventsMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ViewEventsMenuActionPerformed
        // TODO add your handling code here:
        new ViewEvents(user).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_ViewEventsMenuActionPerformed

    private void AddEventsMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddEventsMenuActionPerformed
        new AddEvents(user).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_AddEventsMenuActionPerformed

    private void AddAgentsMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddAgentsMenuActionPerformed
        new UserRegistration(user).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_AddAgentsMenuActionPerformed

    private void ViewAgentsMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ViewAgentsMenuActionPerformed
        // TODO add your handling code here:
        new ViewAgents(user,"agent").setVisible(true);
        this.dispose();
    }//GEN-LAST:event_ViewAgentsMenuActionPerformed

    private void bookingsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bookingsMouseClicked
            // TODO add your handling code here
            new seeBookings(user).setVisible(true);
            this.dispose();
    }//GEN-LAST:event_bookingsMouseClicked

    private void logoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutActionPerformed
        int ans;
        ans = JOptionPane.showConfirmDialog(this,"Do you want to logout!","Logout",JOptionPane.YES_NO_OPTION,JOptionPane.INFORMATION_MESSAGE);
        if(ans==JOptionPane.OK_OPTION)
        {
            new Login().setVisible(true);
            this.dispose();
        }
    // TODO add your handling code here:
    }//GEN-LAST:event_logoutActionPerformed

    private void AddUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddUserActionPerformed
        // TODO add your handling code here:
        new UserRegistration(user).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_AddUserActionPerformed

    private void logoutMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logoutMousePressed
        // TODO add your handling code here:
        int ans;
        ans = JOptionPane.showConfirmDialog(this,"Do you want to logout!","Logout",JOptionPane.YES_NO_OPTION,JOptionPane.INFORMATION_MESSAGE);
        if(ans==JOptionPane.OK_OPTION)
        {
            new Login().setVisible(true);
            this.dispose();
        }
    }//GEN-LAST:event_logoutMousePressed

    private void ViewUsersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ViewUsersActionPerformed
        // TODO add your handling code here:
        new ViewAgents(user,"user").setVisible(true);
        this.dispose();
    }//GEN-LAST:event_ViewUsersActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new AdminPage().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem AddAgentsMenu;
    private javax.swing.JMenuItem AddEventsMenu;
    private javax.swing.JMenuItem AddUser;
    private javax.swing.JMenu AgentsMenu;
    private javax.swing.JMenu EventsMenu;
    private javax.swing.JMenu User;
    private javax.swing.JMenuItem ViewAgentsMenu;
    private javax.swing.JMenuItem ViewEventsMenu;
    private javax.swing.JMenuItem ViewUsers;
    private javax.swing.JLabel WelcomeLabel;
    private javax.swing.JLabel advertlabel;
    private javax.swing.JMenu bookings;
    private javax.swing.JMenu homeMenu;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JMenu logout;
    // End of variables declaration//GEN-END:variables

    private void customiseMenuBar(JMenuBar menuBar) 
    {
        menuBar.setUI(new BasicMenuBarUI() 
        {
            @Override
            public void paint(Graphics g, JComponent c) 
            {
                g.setColor(Color.white);
                g.fillRect(0, 0, c.getWidth(), c.getHeight());
            }
        }
        );
    }
}
